### ISSUE TITLE
Avoid using client-go master

### ISSUE THREAD

**Issue by LiliC** [kinvolk/habitat-operator#34]
Switching to [v4.0.0](https://github.com/kubernetes/client-go/releases/tag/v4.0.0-beta.0) would makes things a bit more stable rather then using master. This release includes [Kubernetes 1.7](https://github.com/kubernetes/client-go/tree/master#compatibility-matrix).

**Comment by asymmetric** [comment]
While I agree it would be better to use a tagged release, please keep in mind that things are "stable" in the sense that everyone installs the exact same commit of each dependency, the one that is specified in the `Gopkg.lock`.

I tried to specify a version, but gave up since it wasn't working, and went with master instead. This might be because 4.0.0 is still in beta.

**Comment by asymmetric** [comment]
4.0.0 [was released](https://github.com/kubernetes/client-go/releases/tag/v4.0.0), which should make fixing this easier.
