### ISSUE TITLE
Handle Ring Key

### ISSUE THREAD

**Issue by LiliC** [kinvolk/habitat-operator#41]
The operator should auto-generate a ring key and/or accept one provided by the user. This way all the containers are secured at the gossip layer.

More info [here](https://www.habitat.sh/docs/run-packages-security/).

**Comment by asymmetric** [comment]
For the time being, we decided to have the operator create the ring key.

This is because a ring, at the moment, only spans within the cluster, and so there is no need for other Services outside of it to join the ring.

Should the encryption be enabled by default?

**Comment by asymmetric** [comment]
Looking at this more, I think it makes more sense, in the first iteration, to use a ring key provided by the user and generated the traditional way, i.e. with `hab ring key generate`.

This is because otherwise we'd have to re-implement the key generation logic in Go. This is definitely possible, and maybe desirable, but I think not a requirement for the first iteration.

**Comment by asymmetric** [comment]
One problem I've encountered is that habitat refuses to load a key if the file is a symlink, as is the case for a Secret mounted via Kubernetes.

I think the culprit is [here](https://github.com/habitat-sh/habitat/blob/master/components/core/src/crypto/keys/mod.rs#L280).

**Comment by asymmetric** [comment]
The bug has been fixed upstream. Waiting for a new release that includes the fix so we can create a new image to run in Kubernetes.
